
- hosts: cloudbreak-deployer
  become: yes
  become_method: sudo
  tasks:

    - name: Upgrade all yum packages
      yum: 
        name: '*'
        state: latest

    - name: Install needed packages
      package:
        name: 
          - iptables-services 
          - net-tools
          - unzip
          - tar
        state: latest

    - name: Flush INPUT chain
      iptables:
        chain: INPUT
        flush: yes

    - name: Flush FORWARD chain
      iptables:
        chain: FORWARD
        flush: yes

    - name: Add the Docker repository (yum)
      yum_repository:
        name: "docker"
        description: "Docker repo centos7"
        baseurl: https://yum.dockerproject.org/repo/main/centos/7
        file: 'docker'
        state: present
        gpgcheck: yes
        gpgkey: https://yum.dockerproject.org/gpg


    - name: Install docker
      package:
        name: 
          - docker-engine-1.9.1 
          - docker-engine-selinux-1.9.1
        state: latest

    - name: Start docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install cloudbreak-deployer
      shell: curl -Ls s3.amazonaws.com/public-repo-1.hortonworks.com/HDP/cloudbreak/cloudbreak-deployer_1.16.4_$(uname)_x86_64.tgz | sudo tar -xz -C /bin cbd

    # Disable SELinux
    - selinux:
        state: disabled

    - name: Creates directory cloudbreak-deployment
      file:
        path: /cloudbreak-deployment
        state: directory     
        mode: 0755

    - name: Create Profile file 
      file:
        path: /cloudbreak-deployment/Profile
        state: touch

    - name: Update Profile file
      blockinfile:
        path: /cloudbreak-deployment/Profile
        block: |
          export UAA_DEFAULT_SECRET={{uaa_default_secret}}
          export UAA_DEFAULT_USER_PW={{uaa_default_user_pw}}
          export PUBLIC_IP=`hostname -i`
        marker: ""


    - name: cbd generate
      command: cbd generate
      args:
        chdir: /cloudbreak-deployment

  
    - name: cbd pull
      command: cbd pull
      args:
        chdir: /cloudbreak-deployment

    - name: cbd start
      command: cbd start
      register: cbd_start
      args:
        chdir: /cloudbreak-deployment

    - name: Print cbd start
      debug: var=cbd_start.stdout_lines

    
    




         